### ISSUE TITLE
Changing the maximum number of Entities in a namespace config does not have any effects

### ISSUE THREAD

**Issue by MuhammadMustafa-IS** [Azure/azure-event-hubs-emulator-installer#22]
**Describe the bug**
I'm trying to add more than 10 Entities to a namespace and I'm getting this error 
```2024-07-01 14:45:55 Unhandled exception. FluentAssertions.Execution.AssertionFailedException: Expected value to be less than or equal to 10 because Max EventHubs supported $10, but found 12 (difference of 2).```

I noticed there is a Config-schema.json that has a definition for the maximum number of entities, but changing it has no effects, I don't see it referenced anywhere too, is it actually used anywhere? 

**Desktop:**
 - OS: Windows

**Emulator Launch Method:**
 - Launcher Script

**Comment by krishankumar95** [comment]
@MuhammadMustafa-IS ;  Config-schema.json should not be changed by the user.  It contains validation rules for user supplied Config.json. 

Using this schema user can validate their Config.json by using any publicly available JSON Schema validators ([Example](https://www.jsonschemavalidator.net))

Max number of entities that can be created for Emulator is 10 ; refer [Emulator Quotas](https://learn.microsoft.com/en-us/azure/event-hubs/overview-emulator#usage-quotas) for more info on quotas enforced by the Emulator:

**Comment by MuhammadMustafa-IS** [comment]
After looking through the Config-Schema.json, I guessed that it was for user to validate his Config.json, thank you for confirming that.
