### ISSUE TITLE
Emulator does not work with Spring Azure Cloud 4.x/5x

### ISSUE THREAD

**Issue by mirkoiv** [Azure/azure-event-hubs-emulator-installer#25]
**Describe the bug**

Azure SDK for Java used in Spring Azure Cloud 4.x/5x does not support 'UseDevelopmentEmulator' connection string parameter.

The results is an 'Illegal connection string parameter name: UseDevelopmentEmulator' exception.

**To Reproduce**

Try to connect to the emulator form an Spring Boot application that use Spring Azure Cloud 4.x/5x.

Feel free to explore the fork, which includes Java and Spring Boot examples, at https://github.com/mirkoiv/azure-event-hubs-emulator-installer. Please note that this repository contains a workaround solution to the issue, and the 'UseDevelopmentEmulator' parameter has been removed. To reproduce an error, append 'UseDevelopmentEmulator=true' to the connection string.

**Expected behavior**
A Spring Boot application using a Spring Azure Cloud should connect to Event Hubs emulator.

**Desktop:**
 - OS: Windows

**Image Platform-Architecture Used:**
- Linux-amd64

**Docker Version:**
- Docker Version: 20.10.21

**Arguments && Environment variables to start Emulator:**
- ACCEPT_EULA: Y
- CONFIG_PATH: EventHub-Emulator\Config\Config.json

**Emulator Launch Method:**
 - Launcher Script

**Additional context:**

**Comment by Balachandra-14** [comment]
@mirkoiv Resolved the connection string issue causing the exception Illegal parameter name: 'UseDevelopmentEmulator' in the Azure Java SDK version 5.15.0. 

Refer to the Java Spring Boot snippet for usage details.
https://github.com/Azure/azure-event-hubs-emulator-installer/tree/main/Sample-Code-Snippets/Java/Spring-Boot

**Comment by ssrahul96** [comment]
@krishankumar95 , could you provide details if the fix is ported to `com.azure:azure-messaging-eventhubs` as well?
