### ISSUE TITLE
can you modify the path in repo `.NET/EventHubs-Emulator-Demo` to `dotnet/EventHubs-Emulator-Demo`

### ISSUE THREAD

**Issue by cicorias** [Azure/azure-event-hubs-emulator-installer#33]
Reason is that on "nix" systems any folder or file that starts with a `.` pretends to be hidden.

**Comment by krishankumar95** [comment]
Community contribution : [#34](https://github.com/Azure/azure-event-hubs-emulator-installer/pull/34) fixes this issue along with addition of docker resources cleanup only mode for Linux and Mac launch scripts.
