### ISSUE TITLE
Error: getaddrinfo ENOTFOUND localhost:5672

### ISSUE THREAD

**Issue by cawoodm** [Azure/azure-event-hubs-emulator-installer#42]
We are unable to connect to the local emulator from any application (C# Azure Function, NodeJS Sample Apps...).

Docker is running in WSL under Windows:
```
docker ps
CONTAINER ID   IMAGE                                                         COMMAND                  PORTS                                                                                            NAMES
9cde40a1b66e   mcr.microsoft.com/azure-messaging/eventhubs-emulator:latest   "/Eventhubs_Emulator…"   0.0.0.0:5672->5672/tcp, :::5672->5672/tcp, 0.0.0.0:9092->9092/tcp, :::9092->9092/tcp, 8080/tcp   eventhubs-emulator
```

The port 5672 is reachable from Windows e.g. paping:
```
paping localhost -p 5672
paping v1.5.5 - Copyright (c) 2011 Mike Lovell

Connecting to MarcPC [127.0.0.1] on TCP 5672:

Connected to 127.0.0.1: time=1.01ms protocol=TCP port=5672
Connected to 127.0.0.1: time=1.00ms protocol=TCP port=5672
```

Here is an example NodeJS application which fails:
```javascript
const { EventHubProducerClient, EventHubConsumerClient, earliestEventPosition } = require("@azure/event-hubs");

const topic = "some-topic";
const connectionString = "Endpoint=sb://localhost:5672;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=SAS_KEY_VALUE;UseDevelopmentEmulator=true;"

const producerClient = new EventHubProducerClient(connectionString, topic);
const client = new EventHubConsumerClient("cg1", connectionString, topic);

async function main() {
  const subscriptionOptions = {
    startPosition: earliestEventPosition
  };

  const subscription = client.subscribe(
    {
      processEvents: async (events, context) => {
        // event processing code goes here
        console.log("got an event");
      },
      processError: async (err, context) => {
        // error reporting/handling code here
      }
    },
    subscriptionOptions
  );

  sendEvent('hello');
  setInterval(sendEvent, 3000);

  // Wait for a few seconds to receive events before closing
  setTimeout(async () => {
    await subscription.close();
    await client.close();
    console.log(`Exiting sample`);
  }, 30 * 1000);
}

main();

async function sendEvent(msg) {
  const eventDataBatch = await producerClient.createBatch();
  eventDataBatch.tryAdd({ body: "hello" });
  await producerClient.sendBatch(eventDataBatch);
  console.log("sent an event");
}
```

Result:
```
node:internal/process/promises:394
    triggerUncaughtException(err, true /* fromPromise */);
    ^

Error: getaddrinfo ENOTFOUND localhost:5672
    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26) {
  name: 'MessagingError',
  retryable: false,
  code: 'ENOTFOUND',
  errno: -3008,
  syscall: 'getaddrinfo'
}

Node.js v22.7.0
```

Whether `localhost` or `127.0.0.1` makes no difference.

**Comment by vaibhavatul47** [comment]
I just tried with latest version of azure/event-hubs, `5.12.2` and your code snippet worked fine for me with following changes:

1. removed the port number from connection string. Using just `localhost` or `127.0.0.1` works fine.
2. Used `eh1`  for topic-name instead of 'some-topic'

My setup:
- node --version: v22.11.0
- @azure/event-hubs sdk version: 5.12.2
- Emulator started via the `.\Docker-Compose-Template\docker-compose-default.yml`

Your issue might be related to this #11. Ensure you are using correct azure-sdk version & latest image of Emulator.

**Comment by kevinbevers** [comment]
I have the same issue, I am currently checking the logs of the container of the emulator and it the health status is unhealthy.

**Comment by jrichardsz** [comment]
> We are unable to connect to the local emulator from any application (C# Azure Function, NodeJS Sample Apps...).
> 
> Docker is running in WSL under Windows:
> 
> ```
> docker ps
> CONTAINER ID   IMAGE                                                         COMMAND                  PORTS                                                                                            NAMES
> 9cde40a1b66e   mcr.microsoft.com/azure-messaging/eventhubs-emulator:latest   "/Eventhubs_Emulator…"   0.0.0.0:5672->5672/tcp, :::5672->5672/tcp, 0.0.0.0:9092->9092/tcp, :::9092->9092/tcp, 8080/tcp   eventhubs-emulator
> ```
> 
> The port 5672 is reachable from Windows e.g. paping:
> 
> ```
> paping localhost -p 5672
> paping v1.5.5 - Copyright (c) 2011 Mike Lovell
> 
> Connecting to MarcPC [127.0.0.1] on TCP 5672:
> 
> Connected to 127.0.0.1: time=1.01ms protocol=TCP port=5672
> Connected to 127.0.0.1: time=1.00ms protocol=TCP port=5672
> ```
> 
> Here is an example NodeJS application which fails:
> 
> const { EventHubProducerClient, EventHubConsumerClient, earliestEventPosition } = require("@azure/event-hubs");
> 
> const topic = "some-topic";
> const connectionString = "Endpoint=sb://localhost:5672;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=SAS_KEY_VALUE;UseDevelopmentEmulator=true;"
> 
> const producerClient = new EventHubProducerClient(connectionString, topic);
> const client = new EventHubConsumerClient("cg1", connectionString, topic);
> 
> async function main() {
>   const subscriptionOptions = {
>     startPosition: earliestEventPosition
>   };
> 
>   const subscription = client.subscribe(
>     {
>       processEvents: async (events, context) => {
>         // event processing code goes here
>         console.log("got an event");
>       },
>       processError: async (err, context) => {
>         // error reporting/handling code here
>       }
>     },
>     subscriptionOptions
>   );
> 
>   sendEvent('hello');
>   setInterval(sendEvent, 3000);
> 
>   // Wait for a few seconds to receive events before closing
>   setTimeout(async () => {
>     await subscription.close();
>     await client.close();
>     console.log(`Exiting sample`);
>   }, 30 * 1000);
> }
> 
> main();
> 
> async function sendEvent(msg) {
>   const eventDataBatch = await producerClient.createBatch();
>   eventDataBatch.tryAdd({ body: "hello" });
>   await producerClient.sendBatch(eventDataBatch);
>   console.log("sent an event");
> }
> Result:
> 
> ```
> node:internal/process/promises:394
>     triggerUncaughtException(err, true /* fromPromise */);
>     ^
> 
> Error: getaddrinfo ENOTFOUND localhost:5672
>     at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26) {
>   name: 'MessagingError',
>   retryable: false,
>   code: 'ENOTFOUND',
>   errno: -3008,
>   syscall: 'getaddrinfo'
> }
> 
> Node.js v22.7.0
> ```
> 
> Whether `localhost` or `127.0.0.1` makes no difference.

Did you fix your error following the @vaibhavatul47 tips ?

**Comment by jrichardsz** [comment]
> I have the same issue, I am currently checking the logs of the container of the emulator and it the health status is unhealthy.
> 
> Edit: here is the error log
> 
> 2024-11-27 10:18:25 fail: a.D.aDl[0]
> 2024-11-27 10:18:25       Emulator Start up probe Unsuccessful. MetadataStore Health status: Unhealthy BlobStore Health status: Unhealthy
> 2024-11-27 10:18:26 fail: Microsoft.Extensions.Diagnostics.HealthChecks.DefaultHealthCheckService[103]
> 2024-11-27 10:18:26       Health check Emulator Health Check with status Unhealthy completed after 27285.9788ms with message 'Emulator Start up probe Unsuccessful. MetadataStore Health status: Unhealthy BlobStore Health status: Unhealthy'
> 2024-11-27 10:18:26 Retry 1 encountered an exception: Emulator Health Check failed.. Waiting 00:00:00 before next retry.
> It appears that I needed to map the ports of my azurite, otherwise the eventhub emulator could not access the required services. use the default docker compose as stated above.

Yes, blob storage (azurite) is required

**Comment by cawoodm** [comment]
> I just tried with latest version of azure/event-hubs, `5.12.2` and your code snippet worked fine for me with following changes:
> 
> 1. removed the port number from connection string. Using just `localhost` or `127.0.0.1` works fine.
> 2. Used `eh1`  for topic-name instead of 'some-topic'

True - that means the SDK magically connects to `5672` (or `9092`?) and we should only specify `localhost`. That is weird.

**Comment by jrichardsz** [comment]
There is no magic.

- The emulator starts  in the port 5672 with HTTP. There is no way to enable https
- All the microsoft sdks (java, c#, python, node, etc) need only the domain or ip without the port . Here some samples
  - localhost
  - 192.168.y.z
  - acme.servicebus.windows.net
- For enterprise usage, these official sdks use the port 5671 which means HTTPS. You don't need to pass the port. This port is part from the [AMQP standard ](https://www.cloudamqp.com/docs/amqp.html)
- Also if you will use the DefaultAzureCredential, the sdk needs HTTPS. There is no way to change this.
- For localhost demos, the official sdks give us an way to to use HTTP (5072) instead HTTPS(5671): `UseDevelopmentEmulator=true;`
  - If you set this param, the sdk automatically will append the port to the "localhost". 
  - Again, you don't need to pass the port. Check the [readme](https://github.com/Azure/azure-event-hubs-emulator-installer) , and you will not find any reference to the 5672
  - The connection string for sime demos with HTTP and using this emulator should be:

  ```
  Endpoint=sb://localhost;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=SAS_KEY_VALUE;UseDevelopmentEmulator=true;
  ```

> PD: To use this emulator with HTTPS, you will need a nginx, a self signed cert and another docker container. I did it. Let me know if someone need it

> PD: I don't like this emulator. I'm working on a new one with HTTPS support.
