### ISSUE TITLE
Running EventHubs-Emulator-Demo throws System.NotSupportedException

### ISSUE THREAD

**Issue by rhwork** [Azure/azure-event-hubs-emulator-installer#5]
Running EventHubs-Emulator-Demo throws exception:

System.NotSupportedException
  HResult=0x80131515
  Message=The requested protocol version 'AMQP 3 1.0.0' is not supported. The supported version is 'AMQP 0 0.9.1'.
For troubleshooting information, see https://aka.ms/azsdk/net/eventhubs/exceptions/troubleshoot
  Source=Azure.Messaging.EventHubs
  StackTrace:
   at Azure.Messaging.EventHubs.Amqp.AmqpProducer.<CreateBatchAsync>d__42.MoveNext()
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.GetResult()
   at Azure.Messaging.EventHubs.Producer.EventHubProducerClient.<CreateBatchAsync>d__54.MoveNext()
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.GetResult()
   at Azure.Messaging.EventHubs.Producer.EventHubProducerClient.<CreateBatchAsync>d__53.MoveNext()
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Runtime.CompilerServices.ValueTaskAwaiter`1.GetResult()
   at Program.<Send>d__4.MoveNext() in C:\Users\....\source\repos\AzureEventHubsEmulator\azure-event-hubs-emulator-installer\Sample-Code-Snippets\.NET\EventHubs-Emulator-Demo\EventHubs-Emulator-Demo\Program.cs:line 38
   at Program.<Main>d__3.MoveNext() in C:\Users\....\source\repos\AzureEventHubsEmulator\azure-event-hubs-emulator-installer\Sample-Code-Snippets\.NET\EventHubs-Emulator-Demo\EventHubs-Emulator-Demo\Program.cs:line 18
   at Program.<Main>(String[] args)

  This exception was originally thrown at this call stack:
    Microsoft.Azure.Amqp.Transport.AmqpTransportInitiator.OnReadHeaderComplete(Microsoft.Azure.Amqp.Transport.TransportAsyncCallbackArgs)
    Microsoft.Azure.Amqp.ExceptionDispatcher.Throw(System.Exception)
    Microsoft.Azure.Amqp.AsyncResult.End<TAsyncResult>(System.IAsyncResult)
    Microsoft.Azure.Amqp.Transport.AmqpTransportInitiator.ConnectAsyncResult.End(System.IAsyncResult)
    Microsoft.Azure.Amqp.Transport.AmqpTransportInitiator.ConnectAsync.AnonymousMethod__17_1(System.IAsyncResult)
    System.Threading.Tasks.TaskFactory<TResult>.FromAsyncCoreLogic(System.IAsyncResult, System.Func<System.IAsyncResult, TResult>, System.Action<System.IAsyncResult>, System.Threading.Tasks.Task<TResult>, bool)
    Azure.Messaging.EventHubs.Amqp.AmqpConnectionScope.CreateAndOpenConnectionAsync(System.Version, System.Uri, System.Uri, Azure.Messaging.EventHubs.EventHubsTransportType, System.Net.IWebProxy, int, int, System.Net.Security.RemoteCertificateValidationCallback, string, System.TimeSpan)
    Microsoft.Azure.Amqp.FaultTolerantAmqpObject<T>.OnCreateAsync(System.TimeSpan, System.Threading.CancellationToken)
    Microsoft.Azure.Amqp.Singleton<TValue>.GetOrCreateAsync(System.TimeSpan, System.Threading.CancellationToken)
    Microsoft.Azure.Amqp.Singleton<TValue>.GetOrCreateAsync(System.TimeSpan, System.Threading.CancellationToken)
    ...
    [Call Stack Truncated]

Inner Exception 1:
AmqpException: The requested protocol version 'AMQP 3 1.0.0' is not supported. The supported version is 'AMQP 0 0.9.1'.

Running on Windows

**Comment by krishankumar95** [comment]
Can you please share some more details around :
a) How was the Emulator launched ? (Scripts/Docker Compose) 

b) Screenshots of the running container logs and logs from "/home/app/EmulatorLogs/*.log"
For Reference : 
1. Console Logs from Container :
![Screenshot 2024-05-22 at 15 57 40](https://github.com/Azure/azure-event-hubs-emulator-installer/assets/121954204/21626869-fc76-4d09-a58e-8fa1ddb091e4)

2. Logs file that can be shared : 
![Screenshot 2024-05-22 at 16 00 28](https://github.com/Azure/azure-event-hubs-emulator-installer/assets/121954204/365d586d-2791-4948-8dc6-9b7fac008a1e)

**Comment by rhwork** [comment]
Emulator was launched using: azure-event-hubs-emulator-installer\EventHub-Emulator\Scripts\Windows\LaunchEmulator.ps1

Heres the console logs:

![image](https://github.com/Azure/azure-event-hubs-emulator-installer/assets/104686988/a188579b-178e-432a-82f2-44791a4b9216)

Here's the log file:
[log2024052209.txt](https://github.com/Azure/azure-event-hubs-emulator-installer/files/15402254/log2024052209.txt)

**Comment by krishankumar95** [comment]
@rhwork  ,nothing looks out of ordinary on Emulator service side of things. Couple of follow up questions :

a) Did we change anything in the provided sample , especially the EventHub client NuGet version ? 

b) Are we running some other AMQP Broker (Ex : RabbitMQ) on port 5672 as Windows Service or Docker Container ? Since RabbitMQ generally runs with version 0.9.1 of AMQP protocol meanwhile EventHubs and ServiceBus utilise the AMQP 1.0 spec.  You can figure this out by simply running a command in Power-shell : 
```
Get-Process -Id (Get-NetTCPConnection -LocalPort 5672).OwningProcess
```

Sample Output if 5672 is being used by Event-Hubs Emulator container :
```
PS C:\Users\krishankumar> Get-Process -Id (Get-NetTCPConnection -LocalPort 5672).OwningProcess

Handles  NPM(K)    PM(K)      WS(K)     CPU(s)     Id  SI ProcessName
-------  ------    -----      -----     ------     --  -- -----------
   1036      49    97672     145360     323.28  10212   2 com.docker.backend
    178      16     2480       8932       1.03  22092   2 wslrelay

```

**Comment by krishankumar95** [comment]
@rhwork  No worries. Additionally if you need to run both RabbitMQ and EventHub Emulator in parallel you can follow the following steps (Custom port can be any free port as per user I have used 6672 as an example) : 

a) Update /Docker-Compose-Template/docker-compose-default.yml at Line 8-9 as follows :

```
 ports:
      - "6672:5672"
```

b) Update the connection string in the sample console application as :
```
"Endpoint=sb://localhost:6672;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=SAS_KEY_VALUE;UseDevelopmentEmulator=true;"
```
