### ISSUE TITLE
Code samples link is offline or wrong in the readme

### ISSUE THREAD

**Issue by jrichardsz** [Azure/azure-event-hubs-emulator-installer#6]
**Describe the bug**
Code samples link is offline or wrong in the readme

**To Reproduce**

- Access to the readme https://github.com/Azure/azure-event-hubs-emulator-installer

**Expected behavior**
See the examples

**Screenshots**
![image](https://github.com/Azure/azure-event-hubs-emulator-installer/assets/3322836/3454052b-6025-42c1-affd-30fe88b6237e)

```[tasklist]
### Tasks
- [ ] Fix Broken Links in Readme
```

**Comment by krishankumar95** [comment]
Resolved with [PR](https://github.com/Azure/azure-event-hubs-emulator-installer/pull/8). Closing the issue.
