### ISSUE TITLE
[Refer here] link in #[Interacting with Emulator] section in the readme is asking a login

### ISSUE THREAD

**Issue by jrichardsz** [Azure/azure-event-hubs-emulator-installer#7]
**Describe the bug**
More details link in Interacting with Emulator section in the readme is asking a login

**To Reproduce**

- Access to the readme https://github.com/Azure/azure-event-hubs-emulator-installer

**Expected behavior**
Access the link without login or warning the user that this is a protected resource

**Screenshots**
![image](https://github.com/Azure/azure-event-hubs-emulator-installer/assets/3322836/93461427-9cef-4d6d-a9cb-499110060378)

**Comment by krishankumar95** [comment]
Broken link being referred to : "https://review.learn.microsoft.com/en-us/azure/event-hubs/test-locally-with-event-hub-emulator?branch=pr-en-us-272443&tabs=automated-script"

**Comment by krishankumar95** [comment]
Resolved with [PR](https://github.com/Azure/azure-event-hubs-emulator-installer/pull/8). Closing the issue.
