### ISSUE TITLE
Only works with localhost

### ISSUE THREAD

**Issue by jrichardsz** [Azure/azure-event-hubs-emulator-installer#9]
**Describe the bug**
I tried to connect it from c# and nodejs with my local ip  but it does not work.

**To Reproduce**

- I followed the steps of https://mcr.microsoft.com/en-us/product/azure-messaging/eventhubs-emulator/about
- Then I used the official [example](https://learn.microsoft.com/en-us/azure/event-hubs/event-hubs-node-get-started-send?tabs=connection-string%2Croles-azure-portal#send-events) to send an event. 
- **It works when localhost** is used in the connection string. 

```
const connectionString = "Endpoint=sb://localhost;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=SAS_KEY_VALUE;UseDevelopmentEmulator=true;";
const eventHubName = "eh1";
```

![image](https://github.com/Azure/azure-event-hubs-emulator-installer/assets/3322836/199f1f88-ce29-47a8-8327-11e4a65376a6)

- But with my ip something like **192.168.0.10** it doesn't work

```
const connectionString = "Endpoint=sb://192.168.0.10;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=SAS_KEY_VALUE;UseDevelopmentEmulator=true;";
const eventHubName = "eh1";
```
![image](https://github.com/Azure/azure-event-hubs-emulator-installer/assets/3322836/08fca71f-80c0-4476-acff-f99f72253bae)

**Expected behavior**
Send and receive events using localhost or the local ip. If I deploy the emulator in my integration (ci/cd) server I should be able to use the IP of this server.

**Desktop:**
 - OS: Windows & Ubuntu

**Image Platform-Architecture Used:**
- Linux-amd64

**Docker Version:**
- Docker Version:  26.1.1,
- desktop and without docker desktop in linux

**Arguments && Environment variables to start Emulator:**
- ACCEPT_EULA: Y
- CONFIG_PATH: The provided here https://mcr.microsoft.com/en-us/product/azure-messaging/eventhubs-emulator/about#usage

**Emulator Launch Method:**
 - Direct Docker compose

`docker compose up`

**Context:**

- If I start other container in my machine at port **5050**, I can access it with `192.168.0.10:5050` so I can say that **192.168.0.10** works fine for any container except for the event hub emulator 

**Attempts without success:**

- I tried with 127.0.0.1, 0.0.0.0 
- I tried network_mode = host 

**Suggests**

Maybe at the source code level of this emulator, you are not binding to all interfaces. In that case try with: 

- https://stackoverflow.com/a/60066573/3957754

**Comment by krishankumar95** [comment]
Triaged, assigning to @Saglodha to assist with the roadmap/milestone for next release.

**Comment by Saglodha** [comment]
@jrichardsz - We get your concern here. Our team has been working on fixing the behavior. We expect the fix to be shipped with upcoming milestone.

**Comment by krishankumar95** [comment]
@jrichardsz ; this issue has been patched with the latest release. 

Emulator now allows connections from other machines on local network. Example connection string: 
```
"Endpoint=sb://192.168.1.10;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=SAS_KEY_VALUE;UseDevelopmentEmulator=true;"
```

Latest client SDKs need to be used to allow for non-localhost connections with Emulator.

**Comment by richard-leon-130524** [comment]
Let me try. Thank you so much!!!

**Comment by jrichardsz** [comment]
I tried and it is working now, using :

- localhost
- local ip
- host.docker.internal

Now I'm getting another error related to the EventHubTrigger that I will register as a new issue.

Thank you for your support.
